plugins {
	id "fabric-loom" version "1.16.+"
}

version = "${project.mod_version}+${project.minecraft_version_base}"
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

loom {
	mods {
		"tooltiptooltips" {
			sourceSet sourceSets.main
		}
	}
}

repositories {
	maven {
		name = "Sleeping Town"
		url = "https://repo.sleeping.town/"
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Kaleido Config
	include implementation("folk.sisby:kaleido-config:${project.kcfg_version}")
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = "UTF-8"
	it.options.release = 21
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
    inputs.property "archivesName", project.base.archivesName

	["COPYING", "COPYING.LESSER"].each { license ->
		from(license) {
			rename { "${it}_${inputs.properties.archivesName}" }
		}
	}
}
